### ISSUE TITLE
Tool for Expressed fusion genes

### ISSUE THREAD

**Issue by rbottcher** [cancervariants/fusions#12]
Hello,

Since you are working on nomenclature standardization it may be worthwhile to check out our existing work related to the matching of detected fusion genes in RNA-seq data, see https://github.com/yhoogstrate/fuma.

"FuMa (Fusion Matcher) matches predicted fusion events (both genomic and transcriptomic) according to chromosomal location and corresponding annotated genes. It is the organisation of the transcriptome (provided by the user) that forms the basis for FuMa to consider fusion genes to be identical or not. The provided gene annotation can be adjusted to define the biological question. For example, if it is desired to only consider fusion events that occur within exons, FuMa can be provided a list of such regions instead of entire genes."

**Comment by ahwagner** [comment]
Thank you for this feedback. I took a look at [your output formats](https://github.com/yhoogstrate/fuma#-f-output_format) and I think it would be great if FuMa would trial the representation of fusions following our draft specification. Please let me know if this is of interest to you!
