### ISSUE TITLE
Nomenclature for inferred fusions

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/fusions#21]
**Name**
Gordana Raca

**What draft version are you leaving feedback on?**
draft-1

**Please provide any comments you have on the guidelines**
We should have our nomenclature delineate between inferred and directly detected fusions.

**Comment by Laveniya** [comment]
I agree with Gordana - would this be captured in the minimum information model for assayed elements ('assay' component)?

**Comment by ahwagner** [comment]
Yes @Laveniya! This is captured in the information model, but not the nomenclature (yet).
