### ISSUE TITLE
Segment boundaries and fusion builder

### ISSUE THREAD

**Issue by malachig** [cancervariants/fusions#28]
Please use this form to provide feedback for the cross-consortium Gene Fusion guidelines at [fusions.cancervariants.org](https://fusions.cancervariants.org).

**Name**
Malachi Griffith

**Occupation (Optional)**
Associate Professor

**Professional Degrees (Optional)**
PhD

**Institutional Affiliation (Optional)**
Washington University

**Professional Society Affiliation (Optional)**
VICC, GA4GH, ClinGen

**What draft version are you leaving feedback on?**
draft-1

**Please provide any comments you have on the guidelines**

I was testing http://fusion-builder.cancervariants.org/assayed-fusion and had the following observation:

- I entered the following as transcript segments using the "Genomics coordinates, gene" mode: 
- EWSR1: NC_000022.10 29664307 - 29688158
- FLI1: NC_000011.9 128638013 - 128683161

The result was this expression:
NM_005243.4(EWSR1):e.1-31_10+33 ::  NM_002017.5(FLI1):e.3-154_9+2808

My reading of this, starting from the left is that:
- the `NM_005243.4(EWSR1)` segment goes FROM the end of exon `1` and `-` `31` bases in the 5' direction TO (`_`) the start of exon `10` and `+` 33 bases in the 3' direction.   
- the `NM_002017.5(FLI1)` segment goes FROM the end of exon `3` and `-` `154` bases in the 5' direction TO (`_`) the start of exon `9` and then `+` `2808` bases in the 3' direction. 

But the [spec](https://fusions.cancervariants.org/en/latest/information_model.html#structural-elements) says:

**Exon offset**
> A value representing the offset from the segment boundary, with positive values offset towards the 5’ end of the transcript and negative values offset towards the 3’ end of the transcript. Offsets can reference sequence in the intronic space.

That sounds reversed relative to what I am seeing in this example.  Positive values seem to indicate the 3' direction and negative values seem to indicate the 5' direction in my example...

**Comment by malachig** [comment]
In the manuscript in Figure B - Minimal information for the characterization of gene fusions (Panel B) it also seems to depict **a -ve offset as being in the 5' direction**.

**Comment by ahwagner** [comment]
Thanks for catching this @malachig! The spec description was wrong; it should be as indicated in the figure.

**Comment by ahwagner** [comment]
fixed in a055867
