### ISSUE TITLE
Fusion nomenclature discussion (to be proposed to HGVS)

### ISSUE THREAD

**Issue by TanskaAnnna** [cancervariants/fusions#5]
I just created this issue to discuss fusion nomenclature proposed by M Li.

**Comment by TanskaAnnna** [comment]
I think keeping gene name in the nomenclature is crucial because using fusion nomenclature without gene names in clinical reporting wouldn't have any sense to clinicians. Basically we don't want clinicians to go and check each NM_ number to see which genes are involved in the fusion, right?

**Comment by ahwagner** [comment]
Thank you for starting this thread @TanskaAnnna! For those that were not on the 2/10/21 call, we discussed the minimal elements for clinical reporting of chimeric transcripts, with the intention of summarizing and voting on such a system as a recommendation by this group / proposal for adoption by HGVS. The meeting minutes and recording will be made available [here](https://docs.google.com/document/d/17zJIbb5tGRwD3-Udz1r6gaowgFJXekkNRMvwYq3xQFE/view#heading=h.jgez3gxormlq).

A few ideas were proposed in call. To begin, [Marilyn Li's proposal](https://drive.google.com/file/d/1-iVgHRucAaPuRzd-MKAycp5_5-6jfSO7/view?usp=sharing):
![image](https://user-images.githubusercontent.com/811065/107584601-bfc72f80-6bca-11eb-9956-5102ccf16ce3.png)

**Comment by ahwagner** [comment]
Next, a suggestion from @dsonkin on an approach that may be more palatable to HGVS:

```
NM_002354.2:r.-358_555::NM_000251.2:r.212_*279 (exon8::exon11)
```

Here, the current HGVS format is followed by exons. Later discussion in the call clarified we would still want to have gene names listed. Also proposed was the idea that partial exons could be indicated, e.g. ```exon8-partial::exon11```

**Comment by ahwagner** [comment]
It was also suggested that we should consider representing fusions in terms of genomic rearrangements, similar to the style presented by St. Jude's fusion visualization tools. This screenshot was presented in call:

<img width="947" alt="Screen Shot 2021-02-10 at 4 33 02 PM" src="https://user-images.githubusercontent.com/811065/107587884-9a3d2480-6bd0-11eb-81ce-07b2b29c71a5.png">

**Comment by ahwagner** [comment]
Also worth mentioning the previously described NCI internal fusion specification (Thomas Coard, Anna Lu, Jennifer Lee):

![image](https://user-images.githubusercontent.com/811065/68897019-48b69900-06f2-11ea-9453-b67011bede6f.png)

**Comment by OSUcat03** [comment]
I'm sorry to have missed the 10th Feb call (also apologies if this should live on one of the other open comment board), but I'm wondering if during our discussions of these gene fusions (and their products), we might look to harmonize across groups regarding gene product nomenclature? In another working group I'm involved with (including representatives from HGNC), we produced this recommendation: [https://www.pnas.org/content/118/3/e2025207118]. Short points: "We recommend standardizing human protein nomenclature through the use of a Human Genome Organisation (HUGO) Gene Nomenclature Committee
(HGNC) gene symbol accompanied by its unique HGNC ID." Just a suggestion to incorporate in our discussion regarding the reporting of gene fusions. I think there could be an argument made for not harmonizing (focusing on the fusion nomenclature only), but I wanted to bring this up as an opportunity for the group.

**Comment by ahwagner** [comment]
Thanks @OSUcat03. Sorry for the delay, just saw your comment. I like the recommendation for use of HGNC ID, it aligns with our recommendations in [VRS](https://vrs.ga4gh.org/en/1.2.0.rc0/terms_and_model.html#gene) as well. I'll keep this in mind during the upcoming discussions on this topic.

**Comment by ahwagner** [comment]
Our current recommendation for fusion gene product nomenclature is missing a few components:

1. Representation of genome-aligned sequence (_templated_ sequence) which is not immediately adjacent to included exons
2. How to represent exon ranges for internal transcript segments in 3+ partner chimeric transcripts
3. How to represent offsets

Some additional points of consideration:
It was mentioned that a more compact nomenclature could be specified by shortening `exon` to `e`. Shortening to the similar form of `e.` (including a dot) seems like an HGVS-aligned way to represent this notion, and enables us to alternatively use `g.` as needed for representing concern 1 above. `e.` is not a [reserved (pre-existing) prefix](http://varnomen.hgvs.org/recommendations/general/) in HGVS 20.05

**Comment by jeselle** [comment]
As mentioned during the 9/15 meeting, exon ranges could also be represented using something similar to a set notation. Since underscores are already being used elsewhere, do you think bracketing the ranges could be more intuitive?

Example from the meeting (or similar): 
`NM_152263.2(EPCAM):exon5::NM_12345.6(TEST1):exon8+3_3-4::NM_002609.3(MSH2):exon2`
Example with bracketed range:
`NM_152263.2(EPCAM):exon5::NM_12345.6(TEST1):exon[8+3,3-4]::NM_002609.3(MSH2):exon2`

(Side note: this example uses the offset notation also presented on 9/15.)

**Comment by jeselle** [comment]
One other thought is to use curly braces instead of brackets for a range notation. The only other place curly brackets are used in HGVS seems to be mitochondrial variants.
See the third-to-last bullet point on this page: https://varnomen.hgvs.org/bg-material/refseq/

**Comment by ahwagner** [comment]
A first draft of a unified nomenclature is available [here](https://lucid.app/lucidspark/7660461e-641b-47b3-8fa3-6576800118d6/edit?invitationId=inv_0f2dd966-edfc-4533-8c15-909f0ee77426). This covers both regulatory and structural fusions, but no representation of information relevant specifically to either categorical or assayed fusions.

**Comment by ahwagner** [comment]
An issue was raised today about other nomenclatures for regulatory element representation. As far as I know there are no nomenclatures that cover the scope we are considering, which includes:

- Regulatory element type
- Optional notation of regulatory element by reference OR by position
- Optional notation of gene associated with regulatory element

One previously published system considered was the [tunicate genome cis-regulatory nomenclature](https://onlinelibrary.wiley.com/doi/10.1002/dvg.22822#:~:text=A%20cis%2Dregulatory%20region%20identifier%20is%20of%20the%20form%3A%20%5BSpecies%5D.REG.%5Bassembly%5D.%5Bstart%2Dend%5D(%7C%5Btarget%20gene%20symbol1%5D%7C%5BTarget%20gene%20symbol2%5D%7C.)).

**Comment by ahwagner** [comment]
An issue was raised today about other nomenclatures for regulatory element representation. As far as I know there are no nomenclatures that cover the scope we are considering, which includes:

- Regulatory element type
- Optional notation of regulatory element by reference OR by position
- Optional notation of gene associated with regulatory element

One previously published system considered was the [tunicate genome cis-regulatory nomenclature](https://onlinelibrary.wiley.com/doi/10.1002/dvg.22822#:~:text=A%20cis%2Dregulatory%20region%20identifier%20is%20of%20the%20form%3A%20%5BSpecies%5D.REG.%5Bassembly%5D.%5Bstart%2Dend%5D(%7C%5Btarget%20gene%20symbol1%5D%7C%5BTarget%20gene%20symbol2%5D%7C.)).

@ayates do you have any insight into other regulatory element nomenclatures we may draw from?
